import './globals.css'


export const metadata = {
  title: 'Trello App',
  description: 'Generated by Geeta',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
